# Local development defaults. Caller-provided variables always win.
exp_default EXP_ROOT "$EXP_REPO_ROOT/.experience-pool-dev"
exp_default EXP_SERVICE_HOST "127.0.0.1"
exp_default EXP_GATEWAY_HOST "0.0.0.0"
exp_default EXP_API_PORT "8080"
exp_default EXP_UI_PORT "3000"
exp_default EXP_GATEWAY_PORT "3080"
exp_default EXP_FLEET_HOST "127.0.0.1"
exp_default EXP_FLEET_PORT "7878"
exp_default EXP_API_WORKERS "1"
exp_default EXP_UI_MODE "dev"
exp_default EXP_GATEWAY_IMPL "node"
exp_default EXP_RATE_LIMIT_ENABLED "0"
exp_default EXP_AUTO_UPLOAD "0"
exp_default EXP_DEFER_OPF "1"
exp_default EXP_LLM "mock"
exp_default EXP_FLEET_ENABLED "0"
exp_default EXP_UI_PUBLIC_URL ""
