# Production defaults. Put host-specific URLs and mount paths in
# production.local.sh; never commit credentials here.
exp_default EXP_ROOT "/var/lib/expool"
exp_default EXP_SERVICE_HOST "0.0.0.0"
exp_default EXP_GATEWAY_HOST "0.0.0.0"
exp_default EXP_API_PORT "8081"
exp_default EXP_UI_PORT "3002"
exp_default EXP_GATEWAY_PORT "3080"
exp_default EXP_FLEET_HOST "127.0.0.1"
exp_default EXP_FLEET_PORT "7878"
exp_default EXP_API_WORKERS "4"
exp_default EXP_UI_MODE "start"
exp_default EXP_GATEWAY_IMPL "node"
exp_default EXP_RATE_LIMIT_ENABLED "1"
exp_default EXP_AUTO_UPLOAD "1"
exp_default EXP_DEFER_OPF "1"
exp_default EXP_LLM "mock"
exp_default EXP_FLEET_ENABLED "0"
exp_default EXP_UI_PUBLIC_URL ""
